### PR TITLE
Harmonic viscosity

### PR DESCRIPTION
**Pull request by roxyboy**
Adding biharmonic viscosity seems to work for a rectangular domain but something funky goes on when the domain is octagonal... I think it has to do with, at the slanted boundaries, the Laplacian being taken with neighboring three grid points that are zero...

### CODE REVIEW

**Comment by jejjohnson** [comment]
> Adding biharmonic viscosity seems to work for a rectangular domain but something funky goes on when the domain is octagonal... I think it has to do with, at the slanted boundaries, the Laplacian being taken with neighboring three grid points that are zero...

That makes sense. I never really understood how to prescribe boundaries. And Louis was doing some shenanigans- [see here](https://github.com/louity/qgm_pytorch/blob/main/QGM.py#L232) - which worked for the rectangular domain but he never shows it for any complex domain.

**Comment by roxyboy** [comment]
If we are really concerned about PV conservation within the domain, it makes physical sense that PV values outside of the domain when padded is prescribed as zero. So I think for the current discretization, it's ok to pad zeros prior to taking the (bi)harmonic dissipation...

**Comment by jejjohnson** [comment]
> If we're really concerned about PV conservation within the domain (which was the whole point of staggering PV as it is), it makes physical sense that PV values outside of the domain when padded is prescribed as zero. So I think for the current discretization, it's ok to pad zeros prior to taking the (bi)harmonic dissipation...

Its not really the physics Im concerned about. Its more…the numerics jaja

**Comment by roxyboy** [comment]
I mean, who's gonna run a double-gyre QG in non-rectangular domains...

**Comment by jejjohnson** [comment]
> I mean, who's gonna run a double-gyre QG in non-rectangular domains...

Certainly not me! I prefer to remove all cooking diffusive coefficients. But it would be nice to know how people handle the (bi-)harmonics on irregular domains. Maybe Bruno might have an idea but I doubt he works with any non-rectangular domains. Or maybe Bill from the qgcm people?

**Comment by roxyboy** [comment]
> Certainly not me! I prefer to remove all cooking diffusive coefficients. But it would be nice to know how people handle the (bi-)harmonics on irregular domains. Maybe Bruno might have an idea but I doubt he works with any non-rectangular domains. Or maybe Bill from the qgcm people?

I'm pretty certain that the only irregular domain within double gyre QG would be where the rectangle is rotated 45 degrees to have it in a slanted diamond shape. And there is an argument to be made for what you call the cooking approach that it is a convergent process where the simulations would converge at sufficiently high enough model resolution and become insensitive to the explicit diffusivity. Implicit diffusivities do not guarantee such convergence with model resolution.

**Comment by roxyboy** [comment]
For explicit viscosity, harmonic viscosity should be enough as a first pass. We'll deal with biharmonic when it comes to it.

**Comment by roxyboy** [comment]
For irregular domains, the boundary conditions become tricky because we need to pad the unmasked region so that `q=0` exactly at the boundary.

**Comment by roxyboy** [comment]
@jejjohnson Are you ok with me merging this for harmonic viscosity?

**Comment by jejjohnson** [comment]
Yup. Looks good. Feel free to merge when you can.

**Pull request merged**
