### PR TITLE
Removing beta planetary vorticity when inverting for total streamfunction

### PR DESCRIPTION
**Pull request by roxyboy**
This PR address issue #11

### CODE REVIEW

**Comment by jejjohnson** [comment]
Does this fix the issue?

**Comment by roxyboy** [comment]
No... hence, I went down the rabbit hole of testing for the advection routine...

**Comment by roxyboy** [comment]
I tested out a run by implementing a crude Arakawa advection scheme and the meridional asymmetry seems to go away... so, it's likely that there's an asymmetry somewhere in our `wenoz` and `upwind` schemes...

**Comment by roxyboy** [comment]
@jejjohnson I'm gonna merge this to move on to work on checking the advection scheme.

**Pull request merged**
